### ISSUE TITLE
Error copying variable of type 'std::atomic<bool>' invokes deleted constructor

### ISSUE THREAD

**Issue by naychrist** [paulhoux/Cinder-Warping#11]
Hi Paul, thanks for the awesome block. Have used it with 086 and love it but am trying to use with 090 for the first time and get 2 of the above errors in Warp.cpp when trying to compile (On OSX 10.10.x with XCode 6.x). Happens with the template as well as my project.

**Comment by paulhoux** [comment]
Should be fixed now. Thanks for notifying me.

**Comment by yangyang233333** [comment]
请问是怎么解决的
