### ISSUE TITLE
please put help.jpg instead of help.png

### ISSUE THREAD

**Issue by brucelane** [paulhoux/Cinder-Warping#13]
hi Paul,
not really an issue, but the jpg file size would be better...

**Comment by brucelane** [comment]
ping Paul -n 1

**Comment by paulhoux** [comment]
In 2016 a few bytes more should not matter much. I don't think I'll change the file. Sorry Bruce.

**Comment by brucelane** [comment]
I have a 128 Gb ssd, size matter to me and I use this block in a lot of projects ;-)
No big deal
