### ISSUE TITLE
image fading to black?

### ISSUE THREAD

**Issue by mhfowler** [paulhoux/Cinder-Warping#15]
Hi Paul, thanks for making this, it seems like it will be really cool!

I am trying to use the example and I'm finding it works except it also fades the inputted image to black in the bottom right corner. Perhaps there is something I'm missing?

Here is an attached image of when I just use the bilinear warp on the help.png image,
and I've also attached an image of what I see when I use the example app without editing at all.

Any help is appreciated (my goal is to warp the image but not have it fade to black). 

Best,
Max

Here is the result with just the bilinear warp:
<img width="1440" alt="screen shot 2017-11-24 at 4 22 03 pm" src="https://user-images.githubusercontent.com/1831536/33224877-d945b498-d133-11e7-9d72-fcd293dbd474.png">

Here is the image without modifying the example code at all:
<img width="1440" alt="screen shot 2017-11-24 at 4 24 42 pm" src="https://user-images.githubusercontent.com/1831536/33224883-05ebbfc4-d134-11e7-9478-ebc1f4c7164b.png">

**Comment by kino-dome** [comment]
Just set the edges to (0, 0, 0, 0), either in your xml file or when creating the warps in your app

**Comment by paulhoux** [comment]
This should be fixed in d4da325eff2b52a05367bbb395587516d7ab5539 . See also https://discourse.libcinder.org/t/paulhoux-cinder-warping/1078/1

Thanks for reporting this.
