### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by kino-dome** [paulhoux/Cinder-Warping#16]
Hi Paul, Thanks for the great block. I noticed that the warping doesn't acknowledge transparency when the texture has alpha channel. Is there a quick fix for this? I guess I should modify the shaders. For a Perspective-Bilinear warp which shader should I modify?

Thanks a bunch

**Comment by kino-dome** [comment]
Found it :) in both of the shaders changed this line:
`fragColor.rgb = texture( uTex0, vertTexCoord1 ).rgb`
to:
`fragColor = texture( uTex0, vertTexCoord1 )`

It seems to work, hope I haven't ruined anything on the side,
Cheers

**Comment by paulhoux** [comment]
Hi @kino-dome , sorry for the late reply. Glad you found a work-around!
