### ISSUE TITLE
Bezier Warp

### ISSUE THREAD

**Issue by alyfreym** [paulhoux/Cinder-Warping#20]
Hi. Hey. Do you have any ideas how to implement this? video -> https://www.youtube.com/watch?v=6H51mRNNHKw
I see that you did something similar. I would be glad to have any ideas, tutorials.

**Comment by paulhoux** [comment]
Hi,

at first glance, it looks very similar to what my BilinearWarp class does, but the interface is different. In the video, they use a Spline-based editor to set the control points. In my code, I simply let the user move points and then I calculate a so-called CatmullRom spline through those points. The result in both the video and my code is a set of splines that together are evaluated to create a mesh. The video texture is then drawn onto the mesh.

There are 2 major differences:
 a) the mesh in the video seems to be able to exhibit a kind of dog ear (page curl) effect, which I don’t think I would be able to replicate with my code.
 b) mesh generation in the video seems dreadfully slow. My code runs quite fast (more than 60 fps) on a single thread on the CPU, even if a large number of splines are used (e.g. 64x64 control points). If needed, it could be converted to a parallel process or compute shader for even more power.

You’re free to use the Cinder-Warping code, by the way. It might give you some insights.

Kind regards,

-Paul

**Comment by alyfreym** [comment]
thanks for the help
